### ISSUE TITLE
Referer is sent to selected URLs

### ISSUE THREAD

**Issue by ndren** [mwmbl/mwmbl#1]
The Referer header "https://mwmbl.org/" is sent to the selected URLs. This can be verified in e.g. the Firefox Network tab, subsection Headers. Could this be disabled?

The simplest way I can find is with the Referrer-Policy header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy. If editing HTTP Headers is not an option, the following works fine too: `<meta name="referrer" content="no-referrer">`.

**Comment by daoudclarke** [comment]
Sounds like a good idea. Do you want to send a PR to fix this?
