### ISSUE TITLE
Remove query parameters from URLs

### ISSUE THREAD

**Issue by brunexgeek** [mwmbl/mwmbl#102]
To avoid storing and distributing sensitive information, crawled URLs probably should have query parameters removed. These query parameters can contain user information, session IDs, API keys, and any other sensitive information.

However, doing so may cause issues with some popular services such as YouTube which has a URL format that uses query parameters (e.g. https://www.youtube.com/watch?v=N8HqyuLBqnU being equivalent to https://www.youtube.com/watch/N8HqyuLBqnU) . It may be necessary to include some exceptions to the rule. I ran some basic tests with Google and apparently that's what they do.

EDIT: I did some additional testing and apparently I was mistaken, Google does have results with query parameters (although they seem to be rare).

**Comment by daoudclarke** [comment]
Since we don't use any URLs from users, only URLs that are in links on the web, I don't think there's a concern here.
