### ISSUE TITLE
readme.md - proposed edit

### ISSUE THREAD

**Issue by atomGit** [mwmbl/mwmbl#133]
ref: But what about...?

DDG is hardly an alternative search engine - results are largely from Bing and they do not respect user privacy - DDG was caught multiple times manipulating sensitive (political) search results and violating their privacy policy

missing from the list is one of the most important ones, [Mojeek](https://www.mojeek.com/)

also see [Alternative search engines that are more respectful of your privacy - 12bytes.org](https://12bytes.org/alternative-search-engines-that-are-more-respectful-of-your-privacy/)

**Comment by daoudclarke** [comment]
The whole readme needs rewriting at this point.
