### ISSUE TITLE
this search gives a HTTP 500

### ISSUE THREAD

**Issue by egonw** [mwmbl/mwmbl#142]
https://mwmbl.org/?q=wikidata+project+wetenschappers

![image](https://github.com/mwmbl/mwmbl/assets/26721/09ba7cf4-f6d1-4e7f-aa45-2582e1d8bb9a)

(for me, at least)

**Comment by daoudclarke** [comment]
Thanks! Looking into it...

**Comment by diagonalo** [comment]
close this ?

**Comment by egonw** [comment]
> close this ?

Why? it's still giving a 500

**Comment by diagonalo** [comment]
True. Sorry did not read carefully. Though this was from the all outage from a few days ago.
Can you try and revert the changes if you added that result manually. If not did you use the Firefox extension ?
I think some other users reported something similar where the crawler gets a 500 and it is directly passed on from the server like you describe.

**Comment by egonw** [comment]
Another example: https://mwmbl.org/?q=matthew+conroy+lipid+maps

**Comment by daoudclarke** [comment]
Fixed by #155
