### ISSUE TITLE
Can't add URLs to a query

### ISSUE THREAD

**Issue by anijatsu** [mwmbl/mwmbl#158]
Query: tiny whelps green wow dragonflight meta raid achievement
URL: https://www.wowhead.com/achievement=19393/whelp-im-lost
Returns me to https://mwmbl.org/?new_url=https%3A%2F%2Fwww.wowhead.com%2Fachievement%3D19393%2Fwhelp-im-lost rather than adding the URL to the results

**Comment by diagonalo** [comment]
Have you tried changing the link or adding a second time ?

**Comment by diagonalo** [comment]
Actually I just did that for you so can close the issue.

**Comment by daoudclarke** [comment]
@anijatsu thanks for reporting, will take a look!

**Comment by anijatsu** [comment]
I found that this behavior only occurs with the Firefox Mwmbl addon enabled and with the "Search Google" option on.
I have made another ticket under mwmbl/crawler-extension/issues/45. I think this issue can be closed, unless it turns out to be somehow correlated anyway?
