### ISSUE TITLE
Determine whether or not we still need to uninstall numpy on EMR

### ISSUE THREAD

**Issue by setop** [mwmbl/mwmbl#19]
can you comment why pip uninstall need to be invoked three times in a row 

https://github.com/mwmbl/mwmbl/blob/03ca368b2acb1a23edb839df7884452d7c26f81d/indexer/bootstrap.sh#L5

please

**Comment by daoudclarke** [comment]
Haha yes I had a stupid issue installing dependencies on EMR and read on stackoverflow somewhere that this was a solution - but actually I can't remember what solved it now.

**Comment by daoudclarke** [comment]
Here is the link: https://stackoverflow.com/a/63506472

We should probably try removing this code and see if it still works, I think it probably does.
