### ISSUE TITLE
HTTP 504 Gateway Timeout on mwmbl.org

### ISSUE THREAD

**Issue by bernardpaulus** [mwmbl/mwmbl#198]
Hi!

Curious about this opensource search engine but it is currently returning an HTTP 504 Gateway Timeout.

![Screenshot from 2024-08-11 00-19-13](https://github.com/user-attachments/assets/11a1646f-1bc1-4e2e-99be-339a1d4e85a0)

I hope this finds you :heart: 

Edit: Firefox 128.0.3 (64bits) on Linux Mint 21.3

**Comment by haexwise** [comment]
I can recommend using https://beta.mwmbl.org for intermittent use. It has all the same functionalities and uses the same index as far as I know.

**Comment by daoudclarke** [comment]
Thanks, currently looking into it!

**Comment by daoudclarke** [comment]
This should be fixed now!
