### ISSUE TITLE
Prioritise root URLs in search ranking

### ISSUE THREAD

**Issue by daoudclarke** [mwmbl/mwmbl#20]
At the moment if you search for "facebook" you will get results about facebook, whereas you should probably get `facebook.com/`. We should prioritise such root URLs if they exist.

**Comment by ColinEspinas** [comment]
Hello,
I think the problem is deeper than that, there are a lot of factors that needs to be considered when it comes to search ranking (meta tags, accessibility, website loading speed, subdomain, sitemaps, etc.).

A starting point could be to establish guidelines on how to rank an URL?

**Comment by daoudclarke** [comment]
True, this is just one thing that needs fixing that people have complained about :smile: 

Guidelines on how to rank a URL sounds like a great idea. All those things you mention sound great. Do you have some thoughts you'd care to jot down?

**Comment by ColinEspinas** [comment]
I don't have deep understanding on how search engine ranking works but I know a few factors that are considered when talking about SEO.

I can look around to see if I find any docs that could help this issue.

**Comment by daoudclarke** [comment]
We now have an evaluation system, so we will only prioritise root URLs if it improves our score in the evaluation.

**Comment by daoudclarke** [comment]
This is effectively done now, via a penalty for long URLs.
