### ISSUE TITLE
Random 500 Internal server errors when trying to curate SERPs

### ISSUE THREAD

**Issue by xynydev** [mwmbl/mwmbl#201]
Every once in a while when attempting to curate search results, the buttons just don't do anything (no indication of error in the front-end). Inspecting console logs reveals that the behavior is caused by internal server errors. 

Here's some details of on of the requests:
![image](https://github.com/user-attachments/assets/13e98c8d-5e6a-4153-bb0e-4d4c0f308263)
![image](https://github.com/user-attachments/assets/b0cd282f-3666-482e-911b-00724fc1bb94)
(`csrfmiddlewaretoken` sent, but redacted from screenshot)
![image](https://github.com/user-attachments/assets/dd0f3e18-998f-4370-8601-45b79ca83a54)

Aside from the error, the request seems normal, and contains the necessary tokens and data and such. The error is intermittent and normal functionality resumes after a while. Likely a server-side issue then?

**Comment by daoudclarke** [comment]
Hey, I think I found the issue and it should be fixed now. For some reason there are now documents being stored in the database without any score, and that was causing an error when we tried to parse the score which came out as a string of "None".

Can you test it and see if it seems to be fixed for you? thanks.

**Comment by xynydev** [comment]
Worked now! I can re-open if I come across this again.
