### ISSUE TITLE
Store index metadata along with index

### ISSUE THREAD

**Issue by daoudclarke** [mwmbl/mwmbl#29]
At the moment, the number of pages and the page size are stored in the code. This doesn't make sense as different indexes can have different page sizes and number of pages. Instead I suggest storing this metadata either:
 1. in the index itself, in which case we could sacrifice the first 4096 bytes for metadata so as to maintain the physical memory page boundaries
 2. or, we could use a separate file stored along with the index.

My current preference is for 1.

**Comment by immortal3** [comment]
I think 1 is the best approach because the index file should have all information for loading and setting up in the main memory. This will save us from so much accidental mismatch between the config file and the original index file.

**Comment by daoudclarke** [comment]
I also thought of
 3. In the filename. We only need to record the page size in the filename since the number of pages can determined from the file size.
