### ISSUE TITLE
Building Image from Dockerfile failed

### ISSUE THREAD

**Issue by raypatterson77** [mwmbl/mwmbl#3]
In Step 14/15 copying the data folder is failing, because the folder is not present.
If I manually create the data folder, the image will build, but I can not start the container: 
`Traceback (most recent call last):

  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.9/site-packages/tinysearchengine/app.py", line 13, in <module>
    tiny_index = TinyIndex(Document, index_path, NUM_PAGES, PAGE_SIZE)
  File "/venv/lib/python3.9/site-packages/tinysearchengine/indexer.py", line 76, in __init__
    self.index_file = open(self.index_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/index.tinysearch'`

Which files have to be present in this data folder?

**Comment by daoudclarke** [comment]
Hi Ray, you need the index file which I haven't committed to Github. I think this is the only file missing. I haven't figured out the best way to offer a download of the current index, but in the meantime we should update the Readme with instructions on how to create an index.

**Comment by nitred** [comment]
@daoudclarke What's the size of the index?

**Comment by healertrix** [comment]
400 mb now

**Comment by daoudclarke** [comment]
The index is currently available at https://storage.googleapis.com/mwmbl/index.tinysearch - we still need to update the docs with the link to this file and instructions on where to put it. The actual size is 100Mb - I remembered wrongly when I said 400Mb.
