### ISSUE TITLE
Use NVMe SSDs for the search index

### ISSUE THREAD

**Issue by yuhong** [mwmbl/mwmbl#35]
There is already a paper on SSD based search engines:
http://pages.cs.wisc.edu/~jhe/fast20-wiser.pdf

**Comment by daoudclarke** [comment]
Nice! thanks for the link. Sorry I missed your issue.

They have slightly different goals to us, although we are both designing for NVMe SSDs. Their system uses up to 50% more storage, whereas we are aiming to vastly reduce the amount of storage needed, in order to reduce the cost per page indexed.

**Comment by yuhong** [comment]
Though I should mention one of the authors of the paper now works for Google, of course.

**Comment by yuhong** [comment]
I really don't care if you are for-profit or non-profit, as long as you are based on NVMe SSDs and your servers aren't using spinning rust to boot from.
