### ISSUE TITLE
Thoughts on using something like Elasticsearch.

### ISSUE THREAD

**Issue by healertrix** [mwmbl/mwmbl#4]
Instead of starting totally from scratch, why don't we use a full-text search engine like elastic search as a starting point?

**Comment by daoudclarke** [comment]
The problem is basically that it's too costly.

**Comment by healertrix** [comment]
Isn't elastic search free and open-source? https://github.com/elastic/elasticsearch

**Comment by healertrix** [comment]
@daoudclarke ?

**Comment by daoudclarke** [comment]
The software is free, but hosting it isn't. I mean too costly in terms of storage and compute power. But I think a proper benchmark comparison would be a good idea to confirm this, will create a new issue.
