### ISSUE TITLE
Command line crawler

### ISSUE THREAD

**Issue by daoudclarke** [mwmbl/mwmbl#45]
It would be nice to have a crawler that can run from the command line for people who have spare server CPU time they would like to donate.

The server should probably start off as a direct translation of the Firefox extension, crawling at random and sending batches of pages to the central server.

We should also modularize it so that where possible we can reuse bits of Rust code within the Firefox extension itself, via WASM.

**Comment by DavidZemon** [comment]
I would love to either spearhead this effort or help with it. @daoudclarke, can you point me at some starting docs or code that is built to receive this stuff? If there's an HTTP RESTful endpoint or something like that, that'd be great and I could build out the Rust project to consume the endpoint.

**Comment by DavidZemon** [comment]
Btw, I did poke around the `crawler/` directory and `crawler/app.py` but didn't see anything obvious that looked like an endpoint where a client would submit results. If I missed something, definitely let me know.

**Comment by daoudclarke** [comment]
This is the line in `crawler/app.py` that gets you a new batch of URLs: https://github.com/mwmbl/mwmbl/blob/master/mwmbl/crawler/app.py#L119 and then you need this to post the result: https://github.com/mwmbl/mwmbl/blob/master/mwmbl/crawler/app.py#L62

**Comment by daoudclarke** [comment]
Sure, no rush!

**Comment by DavidZemon** [comment]
I'm going to use this as some notes, as I investigate how this works. If I don't complete the full investigation of how it works right now, I will come back and edit this comment later.

Crawler client = Chrome extension
Crawler server = `mwmbl/crawler/app.py`

1. Client starts up and reads in a hardcoded list domain names from a JSON file.
2. Client generates (or pulls from Chrome storage) the "user ID" (a random UUID)
3. Client requests a new "batch" (`POST /batches/new`)
4. Server responds with a database call to `get_new_batch_for_user()` (TODO: get details on response type info)
5. Client sequentially iterates over each item in the response and:
   1. Check if robots are allowed and, if not, perform an early return with an object indicating so
      * root domain always allowed
      * If no `robots.txt` at host, default to `true`
      * Lots more logic in `robots.js` that just needs a straight port
    2. Hit the URL and assume response body is text. All exceptions in this process just result in an error object being returned. Non 2xx responses also do an early return with indicating no response found (TODO: Verify that `{error: {name: 'NoResponseText', message: 'No response found'}}` is the right thing to return for a non-2xx status.
    3. Parse the response body as HTML and extract all paragraphs where `classType === good` (TODO: wut dis?)
    4. Coming soon...
    5.

**Comment by pbronez** [comment]
Just discovered the project [via HN](https://news.ycombinator.com/item?id=33258613). Was excited to donate some bandwidth to the crawl, but was turned off by the broad permissions needed by the extension. Would be happy to run the crawler on my homelab though.

The easiest way for me to deploy it would be through [Unraid Community Applications](https://unraid.net/community/apps). That basically adds Docker images to an Unraid-specific App Store. There are several similar projects for other self-hosting OS, most of which work off Docker.

**Comment by daoudclarke** [comment]
That sounds like a great idea.

Incidentally, if you are concerned about the permissions, you can always read the source code to check it's not doing anything you're unhappy with! Unfortunately there's not much we can do to reduce the permissions.

**Comment by omasanori** [comment]
Rust is great but making the existing crawler extension's JS code executable on Deno, Node or such may be reasonable as a short-term solution.

**Comment by daoudclarke** [comment]
This has been implemented in python here: https://github.com/mwmbl/crawler-script

**Comment by thiswillbeyourgithub** [comment]
As mentionned in [that issue](https://github.com/mwmbl/crawler-script/issues/13) it's too bad that the docker image of the crawler is not pushed to docker hub because it's making it harder to use.

That's really too bad because I was making a PR to [the good karma kit](https://github.com/ArchiveBox/good-karma-kit/) to add the mwmbl crawler but can't!

I did find a [docker hub image](https://hub.docker.com/u/mwmbl) that was updated 13h ago and I gave it a go but it crashes asking for an MWMBL_API_KEY and I can't find anywhere in the documentation how to add it.

Similarly, the [mwmbl stats](https://mwmbl.org/stats) mention users by some kind of ID but I don't know how to know who I am!

I just really want to contribute :)

**Comment by daoudclarke** [comment]
Hi @thiswillbeyourgithub - thanks for your message! I am working on a new crawler now that will replace the old one, which was causing a lot of load on the main server.

I hadn't heard of The Good Karma Kit, but it looks cool!

The new crawler requires an API key since the results are logged against your username. If you have a Mwmbl account you can contact me privately (ideally on Matrix) and I can generate an API key for you, since you will be one of the first testers! Eventually we will have a GUI for generating API keys.

**Comment by thiswillbeyourgithub** [comment]
Oh okay thanks!

I put the PR back to draft then, and will await the new crawler.

Thanks for the API offer but I prefer to hold off until it's more official.

Any ETA on when the new crawler will be usable? I don't know what's the preferred way to keep up with the development and the blog seems to be focused on sparser larger updates.

**Comment by thiswillbeyourgithub** [comment]
Hey @daoudclarke 

I was wondering wether you had an ETA on the new crawler or what was the best way to stay up to date on it. Is there a PR I can track? An RSS somewhere?

**Comment by daoudclarke** [comment]
> > Hi [@thiswillbeyourgithub](https://github.com/thiswillbeyourgithub) - thanks for your message! I am working on a new crawler now that will replace the old one, which was causing a lot of load on the main server.
> > I hadn't heard of The Good Karma Kit, but it looks cool!
> > The new crawler requires an API key since the results are logged against your username. If you have a Mwmbl account you can contact me privately (ideally on Matrix) and I can generate an API key for you, since you will be one of the first testers! Eventually we will have a GUI for generating API keys.
> 
> I just found out about this search engine and do want to contribute to it. I created three docker containers on the three sites I control and have them running now.
> 
> If there's a better crawler I'm happy to update them and use that. I'm not on Matrix, but if you tell me how I can get those docker containers running, and give me an API, they'll start working asap.
> 
> Something I was also wondering about is a rough bandwidth estimate per worker and possibly a CPU cost. That way it's easier to estimate how many I can afford to dedicate.

Sure, you can email me at daoud@mwmbl.org with your mwmbl username and I'll get you a key
