### ISSUE TITLE
Search result are super irrelevant

### ISSUE THREAD

**Issue by izzqz** [mwmbl/mwmbl#52]
This project is really cool. But I can't use it while the search result is irrelevant, like in the screenshot below. Any search with 3+ words produces a completely incomprehensible result. I think this is the main issue to work on.

<details>
  <summary><b>Screenshots</b></summary>

  ![image](https://user-images.githubusercontent.com/35831725/173833950-cfb69b5f-0299-473b-a174-be8dc2ce6c2c.png)
  ![image](https://user-images.githubusercontent.com/35831725/173836045-151a60d2-e3a6-4a89-9bb0-db29cbb0df8e.png)
</details>

**Comment by daoudclarke** [comment]
Thanks for your feedback! We've now updated the index and the ranking algorithm, although we still have a long way to go. The main thing is indexing enough pages, which I think is why your first search results are bad. The second example should be improved now.
