### ISSUE TITLE
Inconsistent use of environment variables

### ISSUE THREAD

**Issue by milovanderlinden** [mwmbl/mwmbl#60]
When I look at `app.py`, there are variables set of which some are taken from `os.environ` and some variables are hardcoded. There is a `DATA_DIR` in `paths.py`and `domains.py` and a `DATABASE_URL` in `database.py`

I would like to suggest setting all variables in a single place, f.i. app.py or a newly created settings.py and I would like to suggest using os.environ.get using a default so at least some of the variables will be available even when not set.

**Comment by daoudclarke** [comment]
Fixed by #61
