### ISSUE TITLE
Flood in browser history

### ISSUE THREAD

**Issue by qualterz** [mwmbl/mwmbl#63]
While you typing a query the search results are updating and URL with this query also, there is no need to store intermediary URL queries in browser history, because it is bulking and make history less readable.

<details>
<summary>Screenshot</summary>

![Browser History Flood](https://user-images.githubusercontent.com/38355785/178147296-f2feba62-5e5c-44b8-9f66-8af273d99817.png)

</details>

**Comment by ColinEspinas** [comment]
This is an issue with how we handle the history in the front-end. If you have some time @qualterz could you open an issue on the [front-end repository](https://github.com/mwmbl/front-end/issues)?

**Comment by qualterz** [comment]
Created issue [#20](https://github.com/mwmbl/front-end/issues/20) in front-end repository.
