### ISSUE TITLE
Add some sites to crawler

### ISSUE THREAD

**Issue by daoudclarke** [mwmbl/mwmbl#79]
A request for the following sites to be added to the crawler 

- [codeberg](https://codeberg.org/)
- [lemmy.ml](https://lemmy.ml/)
- [blue flashcards](https://freezingblue.com/flashcards/)
- [odysee](https://odysee.com/)
- [kutt it ](https://kutt.it/)
- [ocean of pdf ](https://oceanofpdf.com/)

Original request: https://github.com/mwmbl/crawler-extension/issues/34

**Comment by EchedeyLR** [comment]
Can I suggest some additional sites too?

What are the requirements?

**Comment by daoudclarke** [comment]
Sure! Any sites that are consistent with [our values](https://book.mwmbl.org/#values) are fine.

Eventually we will have a UI for this. Right now I'm not even sure of the best way to implement it :joy: 

Probably the simplest is to implement a python script that makes a call to the crawler API specifying the URLs that should be added. We might need to make a change to the crawler API because normally we find new sites from existing ones, not from users.

**Comment by EchedeyLR** [comment]
* https://arcmage.org
* https://osgameclones.com

**Comment by nobaraos12** [comment]
https://sepiasearch.org/ if it's possible to index videos from the sites sepiasearch pulls videos from, it's based on peertube

**Comment by nobaraos12** [comment]
1.     Python: https://docs.python.org/3/
2.     Java: https://docs.oracle.com/en/java/
3.     C++: https://devdocs.io/cpp/
4.     C#: https://docs.microsoft.com/en-us/dotnet/csharp/
5.     JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript
6.     PHP: https://www.php.net/docs.php
7.     Ruby: https://ruby-doc.org/
8.     Swift: https://docs.swift.org/
9.     Go: https://golang.org/doc/
10.     R: https://www.rdocumentation.org/
11.    Kotlin: https://kotlinlang.org/docs/reference/
12.     Rust: https://doc.rust-lang.org/book/
13.     Haskell: https://www.haskell.org/documentation/
14.     Elixir: https://hexdocs.pm/elixir/
15.     Lisp: https://lisp-lang.org/documentation/
16.     Ada: https://docs.adacore.com/
17.     Dart: https://dart.dev/guides
18.     Erlang: https://erlang.org/doc/
19.     Julia: https://docs.julialang.org/en/stable/
20.     OCaml: https://ocaml.org/learn/documentation.html
21.     Pascal: https://www.freepascal.org/docs.html
22.     C: https://devdocs.io/c/
23.     FORTRAN: https://gcc.gnu.org/onlinedocs/gfortran/
24.     Prolog: https://www.swi-prolog.org/pldoc/man?section=quickstart
25.     Smalltalk: https://smalltalk.gnu.org/documentation
26.     PL/SQL: https://docs.oracle.com/en/database/oracle/oracle-database/20/lnpls/index.html
27.     COBOL: https://open-cobol.sourceforge.io/
28.     MATLAB: https://www.mathworks.com/help/index.html
29.     Tcl: https://www.tcl.tk/man/tcl8.6/
30.     Lua: https://www.lua.org/manual/5.4/

**Comment by daoudclarke** [comment]
@nobaraos12 that is a great list - thanks!

**Comment by daoudclarke** [comment]
This can be done using the command line crawler here: https://github.com/mwmbl/crawler-script
Closing this as there is no software work to be done (someone just needs to run the above sites through the script).
